### ISSUE TITLE
Use union type instead of enum

### ISSUE THREAD

**Issue by hems** [wnz99/tvcd#49]
[This article explain some interesting concepts on unin type VS enum](https://www.becomebetterprogrammer.com/typescript-union-types-vs-enums/#:~:text=You%20will%20see%20a%20difference,can%20run%20a%20quick%20test.)

From some tests i did, string union type provide a better autocomplete experience on VSCode when filling function parameters ( as an end user ).

So when calling functions users can directly type the string value ( and see all options listed on VSCode ) instead of having to import the Enum and use the Enum.

Of course that's a minor detail in implementation, so low priority..

In case that would be implemented we would have an enum like that

````ts
export enum Exchanges {
  'binance' = 'binance',
  'binancefuturescoin' = 'binancefuturescoin',
  'binancefuturesusd' = 'binancefuturesusd',
  'bitfinex' = 'bitfinex',
  'bitmex' = 'bitmex',
  'bittrex' = 'bittrex',
  'deversifi' = 'deversifi',
  'gateio' = 'gateio',
  'kucoin' = 'kucoin',
  'poloniex' = 'poloniex',
  'valr' = 'valr',
}
````

But function arguments that require exchange names as parameters would have type `Exchanges` instead of `ExchangesEnum`

````ts
export type Exchanges = 
  'binance' | 
  'binancefuturescoin' | 
  'binancefuturesusd' |
  ...
````

**Comment by wnz99** [comment]
yes, agree, you right.

Done in this version: https://github.com/wnz99/tvcd/releases/tag/v1.7.1
