### ISSUE TITLE
Invalid timeframe request on Bitfinex triggers loads of requests

### ISSUE THREAD

**Issue by hems** [wnz99/tvcd#51]
Today i accidentally tried to ask for `3H` candle instead of `3h` candle for Bitfinex.

For some reason it triggered tons of requests for Bitfinex and screwed my rate limit.

<img width="1543" alt="image" src="https://user-images.githubusercontent.com/27327/207859437-6ab94e39-4091-4b5e-af54-7cbae1fe5657.png">

Those are some expectations / suggestions

 - If i send `3H` or `3h` the library should be able to "translate" it to the right format, TLDR: allow users to use lowercase or uppercase for the letters perhaps looking at [this issue](https://github.com/wnz99/tvcd/issues/47) could help standardize it
 - The library to normalise the timeframes, for instance `3h` has lowercase `h` but `1D` has uppercase `D`
 - If the library can't determine the timeframe, don't do a request with `undefined` on the URL ( see screenshot )

**Comment by wnz99** [comment]
hmm, I'll go for the 3rd option, the library will now check if an interval is supported and, if not, it will throw an error: https://github.com/wnz99/tvcd/pull/61

The other options would be good to, but there are a few tricky potential issues, for example `1M` is for months, so it would clash with `1m` for minutes.

I remember I took inspiration from bitfinex for the naming. Bitfines has:

```
TimeFrame
string
required

Available values: '1m', '5m', '15m', '30m', '1h', '3h', '6h', '12h', '1D', '1W', '14D', '1M'
```

**Comment by hems** [comment]
Good point!

Maybe we could use 30d or 30D instead of 1M tough as that is really unusual timeframe to be used it wouldn't affect most people.

Maybe worth checking how vercel does the 30D thing: https://github.com/vercel/ms
